{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-transform-spi",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "booster-transform-spi-4.13.0.jar",
          "url": "booster-transform-spi-4.13.0.jar",
          "size": 29263,
          "sha512": "bc9e9b165a581a779c5d69cc7adecf736d5d9392c2c45efa23da2df1f75242d648e9be13266de9b7596e44ac079d7907e3ce374aedb53a90d4eafb9eedf4bc34",
          "sha256": "53a5eba0059472352e178d9d328cc4ad1e56ca2b87319a17adbe811322148392",
          "sha1": "b6444ff896f0fc6a956555e863516c6235714286",
          "md5": "00dd7ea4c92754fd56d0278b6a533e2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "booster-transform-spi-4.13.0.jar",
          "url": "booster-transform-spi-4.13.0.jar",
          "size": 29263,
          "sha512": "bc9e9b165a581a779c5d69cc7adecf736d5d9392c2c45efa23da2df1f75242d648e9be13266de9b7596e44ac079d7907e3ce374aedb53a90d4eafb9eedf4bc34",
          "sha256": "53a5eba0059472352e178d9d328cc4ad1e56ca2b87319a17adbe811322148392",
          "sha1": "b6444ff896f0fc6a956555e863516c6235714286",
          "md5": "00dd7ea4c92754fd56d0278b6a533e2a"
        }
      ]
    }
  ]
}
