{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-android-gradle-v3_4",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v3_4-4.13.0.jar",
          "url": "booster-android-gradle-v3_4-4.13.0.jar",
          "size": 20816,
          "sha512": "82f48d1ef703a07eed4a5a90a78161855704497623738972fa7416011fdf5a02e3aa05cfab9d22d5ff1885dd79634d2d701b085780ad8d80379d554bf18796db",
          "sha256": "43455d1baa13c9c4f8adf8ed56848bccddc42bdd400ec2088cf15585dd510d8c",
          "sha1": "1c7e727b4955a797489ba373b8f786eb34b9e4ce",
          "md5": "f03ab73a7164a3a953087f107340f3da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v3_4-4.13.0.jar",
          "url": "booster-android-gradle-v3_4-4.13.0.jar",
          "size": 20816,
          "sha512": "82f48d1ef703a07eed4a5a90a78161855704497623738972fa7416011fdf5a02e3aa05cfab9d22d5ff1885dd79634d2d701b085780ad8d80379d554bf18796db",
          "sha256": "43455d1baa13c9c4f8adf8ed56848bccddc42bdd400ec2088cf15585dd510d8c",
          "sha1": "1c7e727b4955a797489ba373b8f786eb34b9e4ce",
          "md5": "f03ab73a7164a3a953087f107340f3da"
        }
      ]
    }
  ]
}
