{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-android-gradle-api",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.didiglobal.booster",
          "module": "booster-kotlinx",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-api-4.13.0.jar",
          "url": "booster-android-gradle-api-4.13.0.jar",
          "size": 57409,
          "sha512": "1c9c12582188e94505212ec9f0c4da3019ce7785a07ac04f2769f19ca6ffb38c7c3bcad8d5123f61202c4f5f0f8e645f2323792a01e82b5eb26ca4761fd85d15",
          "sha256": "2cb77b8bf0e11df176ce4690d2e8530b123aedc95c1ea70bb9f4e53d46a6f334",
          "sha1": "3531e03a8ea52315137f63f7141b27b9f98ad395",
          "md5": "f8dad438872b671b5577fd2ae9537656"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-v3_3",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-v3_4",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-v3_5",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-v3_6",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-v4_0",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-v4_1",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-v4_2",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-v7_0",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-v7_1",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-v7_2",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-kotlinx",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-api-4.13.0.jar",
          "url": "booster-android-gradle-api-4.13.0.jar",
          "size": 57409,
          "sha512": "1c9c12582188e94505212ec9f0c4da3019ce7785a07ac04f2769f19ca6ffb38c7c3bcad8d5123f61202c4f5f0f8e645f2323792a01e82b5eb26ca4761fd85d15",
          "sha256": "2cb77b8bf0e11df176ce4690d2e8530b123aedc95c1ea70bb9f4e53d46a6f334",
          "sha1": "3531e03a8ea52315137f63f7141b27b9f98ad395",
          "md5": "f8dad438872b671b5577fd2ae9537656"
        }
      ]
    }
  ]
}
