{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-android-gradle-v4_2",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v4_2-4.13.0.jar",
          "url": "booster-android-gradle-v4_2-4.13.0.jar",
          "size": 20992,
          "sha512": "a7c1539fa02ccfac846ba74d886096ca65268cde5d6b200fd8a94691a2ced1e138ae509ba7d089d1cc8949a1e2106b653dde86f714b57f29abfe634a7300fd85",
          "sha256": "d576ce2ef77460151657e93bae78f37d9245bd6b3b5a3a6a6bb6026003b54b35",
          "sha1": "ae1e45ecaf09a77b7d45b466c282a528c7b727ce",
          "md5": "de2eec6082fba0c0135b91c3c7e18a60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v4_2-4.13.0.jar",
          "url": "booster-android-gradle-v4_2-4.13.0.jar",
          "size": 20992,
          "sha512": "a7c1539fa02ccfac846ba74d886096ca65268cde5d6b200fd8a94691a2ced1e138ae509ba7d089d1cc8949a1e2106b653dde86f714b57f29abfe634a7300fd85",
          "sha256": "d576ce2ef77460151657e93bae78f37d9245bd6b3b5a3a6a6bb6026003b54b35",
          "sha1": "ae1e45ecaf09a77b7d45b466c282a528c7b727ce",
          "md5": "de2eec6082fba0c0135b91c3c7e18a60"
        }
      ]
    }
  ]
}
