{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-build",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.didiglobal.booster",
          "module": "booster-kotlinx",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-annotations",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-build-4.13.0.jar",
          "url": "booster-build-4.13.0.jar",
          "size": 9415,
          "sha512": "fa034ea85a5a6c4b5c33acee2805a680b155ff1bef30b8d0cf48102dd3773191e4f4c8b79141303c3f2bc99af2c494c82a6280f059263ca7f436819563207017",
          "sha256": "d84891033edce407ac3582576de09ac0c26b4c66fd4cf87c34c4223ad6c9d205",
          "sha1": "e887746643a0846d3f4bf0b042753d411edd4bb2",
          "md5": "299e38b6c49be4cc7a5ef12939daaf3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-kotlinx",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-annotations",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-build-4.13.0.jar",
          "url": "booster-build-4.13.0.jar",
          "size": 9415,
          "sha512": "fa034ea85a5a6c4b5c33acee2805a680b155ff1bef30b8d0cf48102dd3773191e4f4c8b79141303c3f2bc99af2c494c82a6280f059263ca7f436819563207017",
          "sha256": "d84891033edce407ac3582576de09ac0c26b4c66fd4cf87c34c4223ad6c9d205",
          "sha1": "e887746643a0846d3f4bf0b042753d411edd4bb2",
          "md5": "299e38b6c49be4cc7a5ef12939daaf3d"
        }
      ]
    }
  ]
}
