{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-android-gradle-v4_0",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v4_0-4.13.0.jar",
          "url": "booster-android-gradle-v4_0-4.13.0.jar",
          "size": 20669,
          "sha512": "a89647766ac4a5bb8098183608d5b9e15a0f4428168376ce9ddaac6a3be311f93d093bc0e74311e6a73e17e3215c97f6a1ceb44749366912677739d17538733a",
          "sha256": "17c85a22b5d5729b92391cc55e62222662f3f91b46fbfb24a8d7e2261c64d822",
          "sha1": "cc370d9d829324fa631175fb124b92434f911433",
          "md5": "bf77e0fb03b1aab77fd15c0a26de2a8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v4_0-4.13.0.jar",
          "url": "booster-android-gradle-v4_0-4.13.0.jar",
          "size": 20669,
          "sha512": "a89647766ac4a5bb8098183608d5b9e15a0f4428168376ce9ddaac6a3be311f93d093bc0e74311e6a73e17e3215c97f6a1ceb44749366912677739d17538733a",
          "sha256": "17c85a22b5d5729b92391cc55e62222662f3f91b46fbfb24a8d7e2261c64d822",
          "sha1": "cc370d9d829324fa631175fb124b92434f911433",
          "md5": "bf77e0fb03b1aab77fd15c0a26de2a8a"
        }
      ]
    }
  ]
}
