{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-annotations",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "booster-annotations-4.13.0.jar",
          "url": "booster-annotations-4.13.0.jar",
          "size": 2009,
          "sha512": "0a25b2e3c3da74fc30845937f9bddef9a1592e404f7f07d1913e1835a7127218a6e802f42e2f84bc30bedd57043d0b9451efed8fc151f9ab6ea2e97f84a54a66",
          "sha256": "8f99f45f8cce93ac44605888a9a4af77762658cce67f6fc2a9e0e470402b4fee",
          "sha1": "e0915df7536dc689b62dad498474ed36ff7dbee4",
          "md5": "1cb15ac1d1eef4a4a5b5602ba0915a34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "booster-annotations-4.13.0.jar",
          "url": "booster-annotations-4.13.0.jar",
          "size": 2009,
          "sha512": "0a25b2e3c3da74fc30845937f9bddef9a1592e404f7f07d1913e1835a7127218a6e802f42e2f84bc30bedd57043d0b9451efed8fc151f9ab6ea2e97f84a54a66",
          "sha256": "8f99f45f8cce93ac44605888a9a4af77762658cce67f6fc2a9e0e470402b4fee",
          "sha1": "e0915df7536dc689b62dad498474ed36ff7dbee4",
          "md5": "1cb15ac1d1eef4a4a5b5602ba0915a34"
        }
      ]
    }
  ]
}
