{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-android-gradle-v7_1",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v7_1-4.13.0.jar",
          "url": "booster-android-gradle-v7_1-4.13.0.jar",
          "size": 20960,
          "sha512": "9f215e98259af1fdf20ca3df55bb63b4decf05468e15bc9130f861961fdb99cb33c3351d58dc721f90bd70331e49101cd1ddcefddd9971f5332d4d43c0de58d7",
          "sha256": "f05aca615a8664b4a211326ebb3826667dc60ea28b7f3846d0b63f13cb1606c3",
          "sha1": "d2cec22c073f25d225597e285a34ef5f1065c007",
          "md5": "19e7546d0fd4a0d91c6014ed1b202546"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v7_1-4.13.0.jar",
          "url": "booster-android-gradle-v7_1-4.13.0.jar",
          "size": 20960,
          "sha512": "9f215e98259af1fdf20ca3df55bb63b4decf05468e15bc9130f861961fdb99cb33c3351d58dc721f90bd70331e49101cd1ddcefddd9971f5332d4d43c0de58d7",
          "sha256": "f05aca615a8664b4a211326ebb3826667dc60ea28b7f3846d0b63f13cb1606c3",
          "sha1": "d2cec22c073f25d225597e285a34ef5f1065c007",
          "md5": "19e7546d0fd4a0d91c6014ed1b202546"
        }
      ]
    }
  ]
}
