{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-kotlinx",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "booster-kotlinx-4.13.0.jar",
          "url": "booster-kotlinx-4.13.0.jar",
          "size": 57938,
          "sha512": "13fc1df99f4ec9f4357c5aae1ab51abde0e82ea0116c075304e1bbf2924c5d320f1a338bbc32db0dd244b9cbc07412b69159e6bf34b60aaf7d8473356b68a4f1",
          "sha256": "5af97082679909dc873287117d03d9b60ba8456ff304221769b6d8b16a3ac504",
          "sha1": "e56c2f7a6565eb6d5a468746aea36a484d9e1ac1",
          "md5": "121bcbea8d26a36213a8cb79d774a717"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "booster-kotlinx-4.13.0.jar",
          "url": "booster-kotlinx-4.13.0.jar",
          "size": 57938,
          "sha512": "13fc1df99f4ec9f4357c5aae1ab51abde0e82ea0116c075304e1bbf2924c5d320f1a338bbc32db0dd244b9cbc07412b69159e6bf34b60aaf7d8473356b68a4f1",
          "sha256": "5af97082679909dc873287117d03d9b60ba8456ff304221769b6d8b16a3ac504",
          "sha1": "e56c2f7a6565eb6d5a468746aea36a484d9e1ac1",
          "md5": "121bcbea8d26a36213a8cb79d774a717"
        }
      ]
    }
  ]
}
