{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-android-gradle-v3_3",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v3_3-4.13.0.jar",
          "url": "booster-android-gradle-v3_3-4.13.0.jar",
          "size": 20599,
          "sha512": "01ade1205b9cb14decccb9c1dc6ee81aa7d85074a016b5ca09ea17b4d9c55b58727c5c166663b1941502dcac8e527d6c33e11441fd8adb2e183fc5836ba4348b",
          "sha256": "243de058a0d86fde57c183f23dd84bd81f9a8139e106bcbb69a05191cf9bea2e",
          "sha1": "7cde5841612c0ba2994ae195fb8e522a5f82ab07",
          "md5": "7a6e3be24d0782d52d0a82b5e04657fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v3_3-4.13.0.jar",
          "url": "booster-android-gradle-v3_3-4.13.0.jar",
          "size": 20599,
          "sha512": "01ade1205b9cb14decccb9c1dc6ee81aa7d85074a016b5ca09ea17b4d9c55b58727c5c166663b1941502dcac8e527d6c33e11441fd8adb2e183fc5836ba4348b",
          "sha256": "243de058a0d86fde57c183f23dd84bd81f9a8139e106bcbb69a05191cf9bea2e",
          "sha1": "7cde5841612c0ba2994ae195fb8e522a5f82ab07",
          "md5": "7a6e3be24d0782d52d0a82b5e04657fb"
        }
      ]
    }
  ]
}
