{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-api",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-api",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-task-spi",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-spi",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-util",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-api-4.13.0.jar",
          "url": "booster-api-4.13.0.jar",
          "size": 8787,
          "sha512": "7e59569ce6e4eeaabf5b48b558f9dd9c81ee2c875743f0f9e48994bcaadb9741396a97dc74c76ac9cdf5977b9542bb561b3529cc600acab1c3f82183c1045d7e",
          "sha256": "1f8596e855cee7916a25f220b1f33a0ee92fdded3dd57691a51feda3c0dd379f",
          "sha1": "5c5c93433dc191130f3769378a790d964a0a070d",
          "md5": "8775d1ab258f3d68f4eaecceb33fa458"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-api",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-task-spi",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-spi",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-util",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-api-4.13.0.jar",
          "url": "booster-api-4.13.0.jar",
          "size": 8787,
          "sha512": "7e59569ce6e4eeaabf5b48b558f9dd9c81ee2c875743f0f9e48994bcaadb9741396a97dc74c76ac9cdf5977b9542bb561b3529cc600acab1c3f82183c1045d7e",
          "sha256": "1f8596e855cee7916a25f220b1f33a0ee92fdded3dd57691a51feda3c0dd379f",
          "sha1": "5c5c93433dc191130f3769378a790d964a0a070d",
          "md5": "8775d1ab258f3d68f4eaecceb33fa458"
        }
      ]
    }
  ]
}
