{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-task-spi",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "booster-task-spi-4.13.0.jar",
          "url": "booster-task-spi-4.13.0.jar",
          "size": 2061,
          "sha512": "47b5f554a01ab0789ef394265315145b82a111075f1053eb987aae665b3393ca4e32bdd2bac875bdda53f07667e626cfac19ab10d145e86a587ea89b2deb49dc",
          "sha256": "bf30abdab93d53c9f355f3a55f2dbde2d270fd78a1b1ba44b333463f0c526fd2",
          "sha1": "decc6103575fdad791745f0c61f9492e857d9a44",
          "md5": "bfb9bfe4476964e57c922c27fc917c87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "booster-task-spi-4.13.0.jar",
          "url": "booster-task-spi-4.13.0.jar",
          "size": 2061,
          "sha512": "47b5f554a01ab0789ef394265315145b82a111075f1053eb987aae665b3393ca4e32bdd2bac875bdda53f07667e626cfac19ab10d145e86a587ea89b2deb49dc",
          "sha256": "bf30abdab93d53c9f355f3a55f2dbde2d270fd78a1b1ba44b333463f0c526fd2",
          "sha1": "decc6103575fdad791745f0c61f9492e857d9a44",
          "md5": "bfb9bfe4476964e57c922c27fc917c87"
        }
      ]
    }
  ]
}
