{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-android-gradle-v4_1",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v4_1-4.13.0.jar",
          "url": "booster-android-gradle-v4_1-4.13.0.jar",
          "size": 20954,
          "sha512": "f3807c289f06bb3963eac4d3b0925accd2b264ecc98ef573ba4cfde0a45e07524a21e2a5ac68445d345f094ece95b356e7a31eba0032afda7478c6225fa0a68a",
          "sha256": "8345c8762ea133a3682f1a8b8c22b575f862b4eb12427bd9678fd2f728c50da1",
          "sha1": "28c6b92f1c4a19a804099bd97118d30789204bd7",
          "md5": "d8a9c7352690c35948e5b41334411777"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v4_1-4.13.0.jar",
          "url": "booster-android-gradle-v4_1-4.13.0.jar",
          "size": 20954,
          "sha512": "f3807c289f06bb3963eac4d3b0925accd2b264ecc98ef573ba4cfde0a45e07524a21e2a5ac68445d345f094ece95b356e7a31eba0032afda7478c6225fa0a68a",
          "sha256": "8345c8762ea133a3682f1a8b8c22b575f862b4eb12427bd9678fd2f728c50da1",
          "sha1": "28c6b92f1c4a19a804099bd97118d30789204bd7",
          "md5": "d8a9c7352690c35948e5b41334411777"
        }
      ]
    }
  ]
}
