{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-android-gradle-v3_5",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v3_5-4.13.0.jar",
          "url": "booster-android-gradle-v3_5-4.13.0.jar",
          "size": 20066,
          "sha512": "b8b84d065b7cf32f1f3c48824f42a1560b31f4116aa84a17f2b7b5864dfbd49977d3fac35f93fa8892f350667312f8c521269f5e8ea80da35544c9be60e18e2e",
          "sha256": "f597b8f7c0a8c6f830623e360f71ff98b2087bc5219aceba33ff586060c4d973",
          "sha1": "9bdf5910e88adf58a98b2f18f652ceae64dc1504",
          "md5": "842d0541d13d3e030f3971c440862907"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v3_5-4.13.0.jar",
          "url": "booster-android-gradle-v3_5-4.13.0.jar",
          "size": 20066,
          "sha512": "b8b84d065b7cf32f1f3c48824f42a1560b31f4116aa84a17f2b7b5864dfbd49977d3fac35f93fa8892f350667312f8c521269f5e8ea80da35544c9be60e18e2e",
          "sha256": "f597b8f7c0a8c6f830623e360f71ff98b2087bc5219aceba33ff586060c4d973",
          "sha1": "9bdf5910e88adf58a98b2f18f652ceae64dc1504",
          "md5": "842d0541d13d3e030f3971c440862907"
        }
      ]
    }
  ]
}
