{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-android-gradle-v7_2",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v7_2-4.13.0.jar",
          "url": "booster-android-gradle-v7_2-4.13.0.jar",
          "size": 21370,
          "sha512": "fb7ceebf3cbba4ebf1c2a526a788d5dcf3d9033286ba7e36feba7839985e6821e101241260f7064685555a3264c2328ebf90bc729e144b67b49d96623347927b",
          "sha256": "3e9755afc389950e144a41727de62a15208d67879e8dec44c4b38be0cb708c42",
          "sha1": "c0a7d18ebb5345d3339de80f10ff205719e4f282",
          "md5": "c33683426fd1596bb5bdd8adedce8ae6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v7_2-4.13.0.jar",
          "url": "booster-android-gradle-v7_2-4.13.0.jar",
          "size": 21370,
          "sha512": "fb7ceebf3cbba4ebf1c2a526a788d5dcf3d9033286ba7e36feba7839985e6821e101241260f7064685555a3264c2328ebf90bc729e144b67b49d96623347927b",
          "sha256": "3e9755afc389950e144a41727de62a15208d67879e8dec44c4b38be0cb708c42",
          "sha1": "c0a7d18ebb5345d3339de80f10ff205719e4f282",
          "md5": "c33683426fd1596bb5bdd8adedce8ae6"
        }
      ]
    }
  ]
}
