{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-android-gradle-v7_0",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v7_0-4.13.0.jar",
          "url": "booster-android-gradle-v7_0-4.13.0.jar",
          "size": 21107,
          "sha512": "d68fbb9988a12c309c6cba4b90f166f5e87e001bfd7ee2d9e8dbebfc4acab6f9d7809a8a10ea32ba31316072e7cebe8fe58fa77268ee80255af99eeaa3bc58b3",
          "sha256": "60c0a3ef703791b9bb52e0dad8636af914654bd6491d43cfb2950ed254d658b8",
          "sha1": "e891fc7c36a95def1c357c6faecc964504f1f312",
          "md5": "3952c13603a674b71eda17371de94000"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v7_0-4.13.0.jar",
          "url": "booster-android-gradle-v7_0-4.13.0.jar",
          "size": 21107,
          "sha512": "d68fbb9988a12c309c6cba4b90f166f5e87e001bfd7ee2d9e8dbebfc4acab6f9d7809a8a10ea32ba31316072e7cebe8fe58fa77268ee80255af99eeaa3bc58b3",
          "sha256": "60c0a3ef703791b9bb52e0dad8636af914654bd6491d43cfb2950ed254d658b8",
          "sha1": "e891fc7c36a95def1c357c6faecc964504f1f312",
          "md5": "3952c13603a674b71eda17371de94000"
        }
      ]
    }
  ]
}
