{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-android-gradle-v3_6",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v3_6-4.13.0.jar",
          "url": "booster-android-gradle-v3_6-4.13.0.jar",
          "size": 20913,
          "sha512": "0bb5b01c7f4ae7cd2f5c31bc2f0aa0a13c68e7f8f04ca3c246871c09ea271ce031274a88465ab014545b4d323e8cff610ccf654bce486e2098e225f3ceb78ed6",
          "sha256": "2ccb51e7626742723093b228a44475928c437dcfa2f977e94920d91e8e3d2615",
          "sha1": "649848287a3e00414cef7e9073f1d7e019e3a376",
          "md5": "547c85c4cc686638b92f633f8248f7b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-android-gradle-compat",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-v3_6-4.13.0.jar",
          "url": "booster-android-gradle-v3_6-4.13.0.jar",
          "size": 20913,
          "sha512": "0bb5b01c7f4ae7cd2f5c31bc2f0aa0a13c68e7f8f04ca3c246871c09ea271ce031274a88465ab014545b4d323e8cff610ccf654bce486e2098e225f3ceb78ed6",
          "sha256": "2ccb51e7626742723093b228a44475928c437dcfa2f977e94920d91e8e3d2615",
          "sha1": "649848287a3e00414cef7e9073f1d7e019e3a376",
          "md5": "547c85c4cc686638b92f633f8248f7b1"
        }
      ]
    }
  ]
}
