{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-transform-util",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-spi",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-build",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        }
      ],
      "files": [
        {
          "name": "booster-transform-util-4.13.0.jar",
          "url": "booster-transform-util-4.13.0.jar",
          "size": 97061,
          "sha512": "9a5ab5c62a9611164ed413b706a75e5d73b16e74d902bfce7678c30ac078ff43b466e20313f8918f8b928d738bc6e01953688cec9bc35239a84d35dd3bb168b4",
          "sha256": "9bc81f408de82b46b482659a6155d7940f7180020ac86ac584af7873e8bad9e0",
          "sha1": "150c8fdccb8bed33dcd44f52c051976d4a23ae37",
          "md5": "29e2ef76ed82cd227f2fb1e28a05f347"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.10.0.202012080955-r"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-spi",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-build",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        }
      ],
      "files": [
        {
          "name": "booster-transform-util-4.13.0.jar",
          "url": "booster-transform-util-4.13.0.jar",
          "size": 97061,
          "sha512": "9a5ab5c62a9611164ed413b706a75e5d73b16e74d902bfce7678c30ac078ff43b466e20313f8918f8b928d738bc6e01953688cec9bc35239a84d35dd3bb168b4",
          "sha256": "9bc81f408de82b46b482659a6155d7940f7180020ac86ac584af7873e8bad9e0",
          "sha1": "150c8fdccb8bed33dcd44f52c051976d4a23ae37",
          "md5": "29e2ef76ed82cd227f2fb1e28a05f347"
        }
      ]
    }
  ]
}
