{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-android-gradle-compat",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "26.0.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "26.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-compat-4.13.0.jar",
          "url": "booster-android-gradle-compat-4.13.0.jar",
          "size": 19313,
          "sha512": "7640d78126f39b3ad4f5fd786ceff3b3e385335364c8a8cacfe0f405473388bc58b9aa41c3f675accb97dfd73cb7ad0c8d87cc6b0924d93f3e44d4923a2e13f5",
          "sha256": "ff0cec9243fe2ba2b7aa622a2a47ea935b079fc672aa60c6eb04930f969207dc",
          "sha1": "a40902935b76db7ab1f42c35470426e0fdd44059",
          "md5": "f8d4152bd1702d01051e7197349cccbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "26.0.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "26.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-android-gradle-compat-4.13.0.jar",
          "url": "booster-android-gradle-compat-4.13.0.jar",
          "size": 19313,
          "sha512": "7640d78126f39b3ad4f5fd786ceff3b3e385335364c8a8cacfe0f405473388bc58b9aa41c3f675accb97dfd73cb7ad0c8d87cc6b0924d93f3e44d4923a2e13f5",
          "sha256": "ff0cec9243fe2ba2b7aa622a2a47ea935b079fc672aa60c6eb04930f969207dc",
          "sha1": "a40902935b76db7ab1f42c35470426e0fdd44059",
          "md5": "f8d4152bd1702d01051e7197349cccbf"
        }
      ]
    }
  ]
}
