{
  "formatVersion": "1.1",
  "component": {
    "group": "com.didiglobal.booster",
    "module": "booster-transform-asm",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "nlvqqjxmsbcaxkmwsnn36um7lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.didiglobal.booster",
          "module": "booster-annotations",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-util",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-transform-asm-4.13.0.jar",
          "url": "booster-transform-asm-4.13.0.jar",
          "size": 33276,
          "sha512": "d7584691e4b57dea794b9761b58adfe6c68b89c1ac33351a715d761ae1b4502415df9335e89f529a76128c268c795c8ad0ee71b0653ef199ce0a5ae69c607583",
          "sha256": "f48ee9c79a94f0fa33a6ce64bde1a843f0eb4ec41a481e9be412c6901a0a1a78",
          "sha1": "bee9f79da5ac8d7952700ebb6d785ef2b1e20151",
          "md5": "10eada38fb142ffcb8fe3d91b2cc1903"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-annotations",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-util",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "booster-transform-asm-4.13.0.jar",
          "url": "booster-transform-asm-4.13.0.jar",
          "size": 33276,
          "sha512": "d7584691e4b57dea794b9761b58adfe6c68b89c1ac33351a715d761ae1b4502415df9335e89f529a76128c268c795c8ad0ee71b0653ef199ce0a5ae69c607583",
          "sha256": "f48ee9c79a94f0fa33a6ce64bde1a843f0eb4ec41a481e9be412c6901a0a1a78",
          "sha1": "bee9f79da5ac8d7952700ebb6d785ef2b1e20151",
          "md5": "10eada38fb142ffcb8fe3d91b2cc1903"
        }
      ]
    }
  ]
}
